apiVersion: v1
kind: page
spec:
  id: WduAwgm
  title: Default page
  content:
    - component: PageRow
      name: pageRow
      children:
        - component: PageColumn
          name: pageColumn
          layout:
            columnSize: 1
          children:
            - component: PageRow
              name: pageRow1
              props:
                justifyContent: start
              children:
                - component: PageColumn
                  name: pageColumn1
                  layout:
                    columnSize: 1
                  children:
                    - component: Text
                      name: text1
                      props:
                        value: Enter org
                    - component: Text
                      name: text
                      layout:
                        columnSize: 1
                      props:
                        value: Enter repository
                - component: PageColumn
                  name: pageColumn2
                  layout:
                    columnSize: 1
                  children:
                    - component: TextField
                      name: org
                      props:
                        defaultValue: mui
                    - component: TextField
                      name: repo
                      layout:
                        columnSize: 1
                        horizontalAlign: start
                        verticalAlign: center
                      props:
                        defaultValue: mui-toolpad
        - component: Metric
          name: metric1
          layout:
            columnSize: 1
          props:
            value:
              $$jsExpression: |
                queryStargazers.data.repository.stargazerCount
            label: Stargazers Count
            fullWidth: true
    - component: PageRow
      name: pageRow3
      children:
        - component: Text
          name: text2
          props:
            value: ⭐️ ⭐️ ⭐️ Most recent 100 Stargazers ⭐️ ⭐️ ⭐️
            variant: h6
          layout:
            horizontalAlign: center
            verticalAlign: center
    - component: PageRow
      name: pageRow2
      children:
        - component: DataGrid
          name: dataGrid
          props:
            rows:
              $$jsExpression: |
                queryStargazers.data.repository.stargazers.nodes
            columns:
              - field: name
                type: string
                width: 147
              - field: company
                type: string
              - field: email
                type: string
                width: 92
              - field: location
                type: string
              - field: bio
                type: string
              - field: url
                type: link
                width: 179
              - field: followersCount
                type: json
                width: 141
              - field: createdAt
                type: string
                width: 207
            height: 572
  queries:
    - name: queryStargazers
      query:
        function: function.ts#queryStargazers
        kind: local
      parameters:
        - name: owner
          value:
            $$jsExpression: |
              org.value
        - name: repository
          value:
            $$jsExpression: |
              repo.value
