apiVersion: v1
kind: page
spec:
  id: oZWDMVv
  title: Default page
  content:
    - component: PageRow
      name: pageRow1
      children:
        - component: Text
          name: text
          props:
            value: Toolpad GitHub monitoring app
            variant: h3
    - component: PageRow
      name: pageRow3
      children:
        - component: codeComponent.HealthBadge
          name: codeComponent_HealthBadge
          props:
            value:
              $$jsExpression: >
                Math.round((dataGrid.rows.length / countQuery.data) * 10000) /
                100
            lowerIsBetter: false
    - component: PageRow
      name: pageRow
      children:
        - component: DataGrid
          name: dataGrid
          props:
            rows:
              $$jsExpression: |
                listQuery.data
            columns:
              - field: number
                type: string
                width: 80
              - field: title
                type: string
                width: 354
              - field: html_url
                type: link
                width: 323
            height: 502
  queries:
    - name: listQuery
      query:
        kind: rest
        url: https://api.github.com/repos/mui/mui-toolpad/issues
        searchParams:
          - name: labels
            value: 'status: needs triage'
          - name: per_page
            value: '100'
        headers: []
        method: GET
    - name: countQuery
      query:
        kind: rest
        url: https://api.github.com/repos/mui/mui-toolpad
        searchParams: []
        headers: []
        method: GET
        transform: return data.open_issues_count
        transformEnabled: true
  display: standalone
