version: '3.7'
services:
  # Reachable in the dev environment through
  #   TOOLPAD_DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres
  postgres:
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
