services:
  - type: web
    name: toolpad
    env: docker
    region: oregon
    plan: free
    branch: render
    numInstances: 1
    healthCheckPath: /
    dockerfilePath: ./docker/images/render/Dockerfile
    dockerContext: ./docker/images/render

    envVars:
      - key: STUDIO_DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString

databases:
  - name: postgres
    databaseName: db # optional (Render may add a suffix)
    ipAllowList: []
    plan: free
