# https://render.com/docs/preview-environments
previewsEnabled: true

services:
  - type: web
    name: toolpad
    env: node
    buildCommand: yarn --frozen-lockfile --prod=false && yarn release:build
    startCommand: yarn start
    envVars:
      - key: STUDIO_DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString

databases:
  - name: postgres
    ipAllowList: []
    plan: free
