services:
  - type: web
    name: toolpad
    env: docker
    region: oregon
    plan: free
    branch: render
    numInstances: 1
    healthCheckPath: /
    dockerCommand: node_modules/@mui/studio/cli.js --port 80
    dockerfilePath: ./docker/images/studio/Dockerfile
    dockerContext: ./docker/images/studio

    envVars:
      - key: STUDIO_DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString

databases:
  - name: postgres
    databaseName: db # optional (Render may add a suffix)
    ipAllowList: []
    plan: free
