services:
  - type: web
    name: toolpad
    env: node
    buildCommand: yarn && yarn release:build
    startCommand: yarn start
    pullRequestPreviewsEnabled: true
    envVars:
      - key: STUDIO_DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString

databases:
  - name: postgres
    databaseName: db # optional (Render may add a suffix)
    ipAllowList: []
    plan: free
