previewsExpireAfterDays: 3

services:
  - type: web
    name: npm-stats
    env: node
    rootDir: examples/npm-stats
    buildCommand: yarn && yarn build
    startCommand: yarn start
    pullRequestPreviewsEnabled: true
    plan: standard
    envVars:
      - key: NODE_VERSION
        value: 18
