version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0.0

defaults: &defaults
  working_directory: /tmp/mui-studio
  docker:
    - image: circleci/node:14
# CircleCI has disabled the cache across forks for security reasons.
# Following their official statement, it was a quick solution, they
# are working on providing this feature back with appropriate security measures.
# https://discuss.circleci.com/t/saving-cache-stopped-working-warning-skipping-this-step-disabled-in-configuration/24423/21
#
# restore_repo: &restore_repo
#   restore_cache:
#     key: v1-repo-{{ .Branch }}-{{ .Revision }}

commands:
  install_js:
    parameters:
      browsers:
        type: boolean
        default: false
        description: 'Set to true if you intend to any browser (e.g. with playwright).'

    steps:
      - run:
          name: View install environment
          command: |
            node --version
            yarn --version
      - restore_cache:
          name: Restore yarn cache
          keys:
            - v8-yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Set yarn cache folder
          command: |
            # Keep path in sync with `save_cache` for key "v8-yarn-"
            yarn config set cache-folder /tmp/yarn-cache
            # Debug information
            yarn cache dir
            yarn cache list
      - run:
          name: Install js dependencies
          command: yarn install --frozen-lockfile --verbose
          environment:
            PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: <<# parameters.browsers >>0<</ parameters.browsers >><<^ parameters.browsers >>1<</ parameters.browsers >>
      - save_cache:
          name: Save yarn cache
          key: v8-yarn-{{ checksum "yarn.lock" }}
          paths:
            # Keep path in sync with "Set yarn cache folder"
            # Can't use environment variables for `save_cache` paths (tested in https://app.circleci.com/pipelines/github/mui-org/material-ui/37813/workflows/5b1e207f-ac8b-44e7-9ba4-d0f9a01f5c55/jobs/223370)
            - /tmp/yarn-cache

jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - install_js
      - run:
          name: Should not have any git not staged
          command: git diff --exit-code
      - run:
          name: Check for duplicated packages
          command: yarn deduplicate
  test_static:
    <<: *defaults
    steps:
      - checkout
      - install_js
      - run:
          name: '`yarn prettier` changes committed?'
          command: yarn prettier check-changed
      - run:
          name: 'Build packages'
          command: yarn release:build
workflows:
  version: 2
  pipeline:
    jobs:
      - checkout
      - test_static:
          requires:
            - checkout
