version: 2.1

defaults: &defaults
  working_directory: /tmp/mui-toolpad
  resource_class: medium
  docker:
    - image: cimg/node:18.17.1
# CircleCI has disabled the cache across forks for security reasons.
# Following their official statement, it was a quick solution, they
# are working on providing this feature back with appropriate security measures.
# https://discuss.circleci.com/t/saving-cache-stopped-working-warning-skipping-this-step-disabled-in-configuration/24423/21
#
# restore_repo: &restore_repo
#   restore_cache:
#     key: v1-repo-{{ .Branch }}-{{ .Revision }}

commands:
  install_js:
    parameters:
      browsers:
        type: boolean
        default: false
        description: 'Set to true if you intend to use any browser (e.g. with playwright).'

    steps:
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}

      - run:
          name: Install pnpm package manager
          command: |
            corepack enable
            corepack prepare --activate

      - when:
          condition: << parameters.browsers >>
          steps:
            - run:
                name: Prepare playwright hash
                command: pnpm list --json --filter playwright > /tmp/playwright_info.json
            - store_artifacts:
                name: Debug playwright hash
                path: /tmp/playwright_info.json
            - restore_cache:
                name: Restore playwright cache
                keys:
                  - v5-playwright-{{ arch }}-{{ checksum "/tmp/playwright_info.json" }}
      - run:
          name: View install environment
          command: |
            node --version
            pnpm --version
      - run:
          name: Install js dependencies
          command: pnpm install
      - when:
          condition: << parameters.browsers >>
          steps:
            - run:
                name: Install playwright browsers
                command: pnpm playwright install --with-deps
                environment:
                  PLAYWRIGHT_BROWSERS_PATH: /tmp/pw-browsers

      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
      - when:
          condition: << parameters.browsers >>
          steps:
            - save_cache:
                name: Save playwright cache
                key: v5-playwright-{{ arch }}-{{ checksum "/tmp/playwright_info.json" }}
                paths:
                  # Keep path in sync with "PLAYWRIGHT_BROWSERS_PATH"
                  # Can't use environment variables for `save_cache` paths (tested in https://app.circleci.com/pipelines/github/mui/material-ui/37813/workflows/5b1e207f-ac8b-44e7-9ba4-d0f9a01f5c55/jobs/223370)
                  - /tmp/pw-browsers

jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - install_js
      - run:
          name: Should not have any git not staged
          command: git add -A && git diff --exit-code --staged
      - run:
          name: Check for duplicated packages
          command: |
            if [[ $(git diff --name-status master | grep pnpm.lock) == "" ]];
            then
                echo "no changes to dependencies detected, skipping..."
            else
                pnpm dedupe --check
            fi

  test_lint:
    <<: *defaults
    steps:
      - checkout
      - install_js
      - run:
          name: Eslint
          command: pnpm eslint
      - run:
          name: Lint JSON
          command: pnpm jsonlint
      - run:
          name: Lint Markdown
          command: pnpm markdownlint
  test_types:
    <<: *defaults
    steps:
      - checkout
      - install_js
      - run:
          name: Check Typescript types
          command: pnpm check-types
  test_static:
    <<: *defaults
    steps:
      - checkout
      - install_js
      - run:
          name: '`pnpm prettier:all` changes committed?'
          command: |
            pnpm prettier:all
            pnpm check-changes
      - run:
          name: '`pnpm jsonSchemas` changes committed?'
          command: |
            pnpm jsonSchemas
            pnpm check-changes
      - run:
          name: '`pnpm docs:build:api` changes committed?'
          command: |
            pnpm docs:build:api
            pnpm check-changes

  test_unit:
    <<: *defaults

    steps:
      - checkout
      - install_js:
          browsers: false
      - run:
          name: 'Build packages'
          command: pnpm release:build
      - run:
          name: Tests fake browser
          command: pnpm test

  test_integration:
    <<: *defaults
    resource_class: 'large'
    parallelism: 2
    docker:
      - image: mcr.microsoft.com/playwright:v1.41.1-focal
        environment:
          NODE_ENV: test
          TOOLPAD_TEST_RETRIES: 1

    steps:
      - checkout
      - install_js:
          browsers: true
      - run:
          name: 'Build packages'
          command: pnpm release:build
      - run:
          name: Tests real browser
          command: pnpm test:integration
      - store_test_results:
          path: test/test-results/junit.xml
      - run:
          name: Upload screenshots to Argos CI
          command: ARGOS_PARALLEL_TOTAL=${CIRCLE_NODE_TOTAL} pnpm test:argos
      - store_artifacts:
          path: test/test-results
          destination: playwright-test-results

workflows:
  pipeline:
    jobs:
      - checkout
      - test_lint:
          requires:
            - checkout
      - test_types:
          requires:
            - checkout
      - test_static:
          requires:
            - checkout
      - test_unit:
          requires:
            - checkout
      - test_integration:
          requires:
            - checkout
