apiVersion: v1
kind: page
spec:
  id: sR_fqKE
  title: Default page
  queries:
    - name: stories
      query:
        function: getStories
        kind: local
  content:
    - component: PageRow
      name: pageRow
      children:
        - component: List
          name: list
          props:
            renderItem:
              $$template:
                - component: PageRow
                  name: pageRow1
                  children:
                    - component: PageColumn
                      name: pageColumn
                      layout:
                        columnSize: 1
                      children:
                        - component: Text
                          name: text
                          props:
                            value:
                              $$jsExpression: >
                                `[**${stories.data[i].title}**](${stories.data[i].url})`
                            mode: markdown
                        - component: Text
                          name: text1
                          props:
                            value:
                              $$jsExpression: >
                                `${stories.data[i].score} by
                                ${stories.data[i].by} |
                                ${stories.data[i].descendants} comments`
            itemCount:
              $$jsExpression: |
                stories.data.length
