apiVersion: v1
kind: page
spec:
  id: evZC-gp
  title: Default page
  queries:
    - name: query
      query:
        kind: rest
        url:
          $$jsExpression: |
            `https://api.npmjs.org/versions/${encodeURIComponent(
              parameters.package
            )}/last-week`
        headers: []
        method: GET
      parameters:
        - name: package
          value:
            $$jsExpression: |
              textField.value
    - name: query1
      query:
        kind: rest
        url:
          $$jsExpression: >
            `https://api.npms.io/v2/package/${encodeURIComponent(parameters.package)}`
        headers: []
        method: GET
      parameters:
        - name: package
          value:
            $$jsExpression: |
              textField.value
    - name: query2
      query:
        kind: rest
        url:
          $$jsExpression: |
            `https://api.npmjs.org/downloads/point/${parameters.start_date}:${
              parameters.end_date
            }/${encodeURIComponent(parameters.package)}`
        headers: []
        method: GET
      parameters:
        - name: package
          value:
            $$jsExpression: |
              textField.value
        - name: start_date
          value:
            $$jsExpression: |
              datePicker.value
        - name: end_date
          value:
            $$jsExpression: |
              datePicker1.value
  content:
    - component: PageRow
      name: pageRow
      children:
        - component: PageColumn
          name: pageColumn
          layout:
            columnSize: 1
          children:
            - component: DatePicker
              name: datePicker
        - component: TextField
          name: textField
    - component: PageRow
      name: pageRow2
      children:
        - component: DatePicker
          name: datePicker1
    - component: PageRow
      name: pageRow1
      children:
        - component: Text
          name: text
          props:
            value:
              $$jsExpression: |
                query2.data.downloads
    - component: PageRow
      name: pageRow3
      children:
        - component: Text
          name: text1
          props:
            value: Test 123
    - component: PageRow
      name: pageRow4
      children:
        - component: Button
          name: button
          props:
            content: Navigate
            onClick:
              $$navigationAction:
                page: BKxS2c8
                parameters:
                  param1:
                    $$jsExpression: |
                      text1.value
