apiVersion: v1
kind: page
spec:
  id: evZC-gp
  title: Default page
  queries:
    - name: versionLastweek
      query:
        kind: rest
        url:
          $$jsExpression: |
            `https://api.npmjs.org/versions/${encodeURIComponent(
              parameters.package
            )}/last-week`
        headers: []
        method: GET
        searchParams: []
      parameters:
        - name: package
          value:
            $$jsExpression: |
              textField.value
        - name: start_date
          value:
            $$jsExpression: |
              datePicker.value
        - name: end_date
          value:
            $$jsExpression: |
              datePicker1.value
    - name: totalRange
      query:
        kind: rest
        url:
          $$jsExpression: |
            `https://api.npmjs.org/downloads/point/${parameters.start_date}:${
              parameters.end_date
            }/${encodeURIComponent(parameters.package)}`
        headers: []
        method: GET
        searchParams: []
      parameters:
        - name: package
          value:
            $$jsExpression: |
              textField.value
        - name: start_date
          value:
            $$jsExpression: |
              datePicker.value
        - name: end_date
          value:
            $$jsExpression: |
              datePicker1.value
    - name: downloadsRange
      query:
        kind: rest
        url:
          $$jsExpression: |
            `https://api.npmjs.org/downloads/range/${parameters.start_date}:${
              parameters.end_date
            }/${encodeURIComponent(parameters.package)}`
        headers: []
        method: GET
        searchParams: []
      parameters:
        - name: package
          value:
            $$jsExpression: |
              textField.value
        - name: start_date
          value:
            $$jsExpression: |
              datePicker.value
        - name: end_date
          value:
            $$jsExpression: |
              datePicker1.value
  content:
    - component: PageRow
      name: pageRow
      children:
        - component: Text
          name: text1
          props:
            value: Enter package name
            variant: h6
          layout:
            columnSize: 0.49074074074074076
        - component: PageColumn
          name: pageColumn
          layout:
            columnSize: 1.5092592592592593
          children:
            - component: PageRow
              name: pageRow3
              props:
                justifyContent: start
              children:
                - component: TextField
                  name: textField
                  layout:
                    columnSize: 0.8853503184713376
                  props:
                    defaultValue: "@mui/toolpad"
                - component: Text
                  name: text2
                  props:
                    value: Enter date range
                    variant: h6
                  layout:
                    columnSize: 1.111813296178344
                - component: DatePicker
                  name: datePicker
                  layout:
                    columnSize: 1.002808487874465
                  props:
                    defaultValue: 2023-06-01
                - component: DatePicker
                  name: datePicker1
                  props:
                    defaultValue: 2023-06-07
    - component: PageRow
      name: pageRow2
      children:
        - component: codeComponent.LineChart
          name: codeComponent_LineChart
          props:
            data:
              $$jsExpression: |
                downloadsRange.data.downloads
            series:
              - downloads
    - component: PageRow
      name: pageRow5
      children:
        - component: Text
          name: text4
          props:
            value: Total downloads count for the specified duration
            variant: body1
        - component: Text
          name: text
          props:
            value:
              $$jsExpression: |
                totalRange.data.downloads
    - component: PageRow
      name: pageRow4
      children:
        - component: Text
          name: text3
          props:
            value: Version wise data (This is available just for the last week)
    - component: PageRow
      name: pageRow6
      children:
        - component: DataGrid
          name: dataGrid
          props:
            rows:
              $$jsExpression: |
                Object.entries(versionLastweek.data.downloads)
            columns:
              - field: "0"
                type: string
                headerName: Version
                width: 160
              - field: "1"
                type: number
                width: 152
                headerName: No. of downloads
