apiVersion: v1
kind: page
spec:
  id: BKxS2c8
  title: page1
  display: shell
  parameters:
    - name: param1
      value: hi
  content:
    - component: PageRow
      name: pageRow
      children:
        - component: Text
          name: text
