apiVersion: v1
kind: page
spec:
  id: b4UWL4X
  title: Default page
  content:
    - component: PageRow
      name: pageRow2
      children:
        - component: Text
          name: text
          props:
            value: Stripe Dashboard
            variant: h4
    - component: PageRow
      name: pageRow3
      children:
        - component: Text
          name: text1
          props:
            value: Invoices
            variant: h5
    - component: PageRow
      name: pageRow1
      children:
        - component: DataGrid
          name: dataGrid
          props:
            rows:
              $$jsExpression: |
                JSON.parse(listInvoices.data)
            columns:
              - field: id
                type: string
              - field: object
                type: string
              - field: account_country
                type: string
              - field: amount_due
                type: number
              - field: amount_paid
                type: number
              - field: amount_remaining
                type: number
              - field: amount_shipping
                type: number
              - field: collection_method
                type: string
              - field: created
                type: number
              - field: currency
                type: string
              - field: custom_fields
                type: json
              - field: customer
                type: string
              - field: customer_address
                type: json
              - field: customer_email
                type: string
              - field: customer_name
                type: string
              - field: customer_phone
                type: json
              - field: customer_shipping
                type: json
              - field: customer_tax_exempt
                type: string
              - field: customer_tax_ids
                type: json
              - field: default_payment_method
                type: json
              - field: default_source
                type: json
              - field: default_tax_rates
                type: json
              - field: description
                type: json
              - field: discount
                type: json
              - field: discounts
                type: json
              - field: due_date
                type: number
              - field: effective_at
                type: number
              - field: ending_balance
                type: number
              - field: footer
                type: json
              - field: from_invoice
                type: json
              - field: hosted_invoice_url
                type: link
              - field: invoice_pdf
                type: link
              - field: last_finalization_error
                type: json
              - field: latest_revision
                type: json
              - field: lines
                type: json
              - field: livemode
                type: boolean
              - field: metadata
                type: json
              - field: next_payment_attempt
                type: json
              - field: number
                type: string
              - field: on_behalf_of
                type: json
              - field: paid
                type: boolean
              - field: paid_out_of_band
                type: boolean
              - field: payment_intent
                type: string
              - field: payment_settings
                type: json
              - field: period_end
                type: number
              - field: period_start
                type: number
              - field: post_payment_credit_notes_amount
                type: number
              - field: pre_payment_credit_notes_amount
                type: number
              - field: quote
                type: json
              - field: receipt_number
                type: json
              - field: rendering_options
                type: json
              - field: shipping_cost
                type: json
              - field: shipping_details
                type: json
              - field: starting_balance
                type: number
              - field: statement_descriptor
                type: json
              - field: status
                type: string
              - field: status_transitions
                type: json
              - field: subscription
                type: json
              - field: subtotal
                type: number
              - field: subtotal_excluding_tax
                type: number
              - field: tax
                type: json
              - field: test_clock
                type: json
              - field: total
                type: number
              - field: total_discount_amounts
                type: json
              - field: total_excluding_tax
                type: number
              - field: total_tax_amounts
                type: json
              - field: transfer_data
                type: json
              - field: webhooks_delivered_at
                type: number
    - component: PageRow
      name: pageRow
      children:
        - component: Button
          name: button
          props:
            content: Download PDFs
            onClick:
              $$jsExpressionAction: downloadPDFs.call()
            size: medium
            variant: outlined
            loading:
              $$jsExpression: |
                downloadPDFs?.isLoading
            disabled:
              $$jsExpression: |
                listInvoices?.data?.length === 0
  queries:
    - name: downloadPDFs
      mode: mutation
      query:
        function: functions.ts#downloadPDFs
        kind: local
      parameters:
        - name: limit
          value: 10
    - name: listInvoices
      query:
        function: functions.ts#listInvoices
        kind: local
      parameters:
        - name: limit
          value: 10
