apiVersion: v1
kind: page
spec:
  id: oZWDMVv
  title: Default page
  content:
    - component: PageRow
      name: pageRow1
      children:
        - component: Text
          name: text
          layout:
            horizontalAlign: center
          props:
            value: Toolpad GitHub monitoring app
            variant: h3
    - component: PageRow
      name: pageRow2
      children:
        - component: Paper
          name: paper
          children:
            - component: PageRow
              name: pageRow4
              children:
                - component: PageColumn
                  name: pageColumn
                  layout:
                    columnSize: 1
                  children:
                    - component: codeComponent.HealthBadge
                      name: codeComponent_HealthBadge
                      props:
                        value:
                          $$jsExpression: >
                            Math.round((dataGrid.rows.length / countQuery.data)
                            * 10000) / 100
                        lowerIsBetter: false
                    - component: Text
                      name: text1
                      props:
                        value: Issues without scope vs open issues
        - component: Paper
          name: paper3
          layout:
            columnSize: 1
          children:
            - component: PageRow
              name: pageRow6
              children:
                - component: PageColumn
                  name: pageColumn3
                  layout:
                    columnSize: 1
                  children:
                    - component: codeComponent.HealthBadge
                      name: codeComponent_HealthBadge3
                      props:
                        problem: 10
                        value: 2
                        lowerIsBetter: true
                    - component: Text
                      name: text4
                      props:
                        value: A random KPI
    - component: PageRow
      name: pageRow7
      children:
        - component: Paper
          name: paper2
          children:
            - component: PageRow
              name: pageRow5
              children:
                - component: PageColumn
                  name: pageColumn2
                  layout:
                    columnSize: 1
                  children:
                    - component: codeComponent.HealthBadge
                      name: codeComponent_HealthBadge2
                      props:
                        warning: 25
                        problem: 50
                        value: 75
                        lowerIsBetter: true
                    - component: Text
                      name: text3
                      props:
                        value: Another random KPI
        - component: Paper
          name: paper1
          children:
            - component: PageRow
              name: pageRow3
              children:
                - component: PageColumn
                  name: pageColumn1
                  layout:
                    columnSize: 1
                  children:
                    - component: codeComponent.HealthBadge
                      name: codeComponent_HealthBadge1
                      props:
                        value: 0
                        unit: issues
                        lowerIsBetter: true
                    - component: Text
                      name: text2
                      props:
                        value: Count of issues without label
    - component: PageRow
      name: pageRow
      children:
        - component: DataGrid
          name: dataGrid
          props:
            rows:
              $$jsExpression: |
                listQuery.data
            columns:
              - field: number
                type: string
                width: 80
              - field: title
                type: string
                width: 331
              - field: html_url
                type: link
                width: 377
            height: 458
  queries:
    - name: listQuery
      query:
        kind: rest
        url: https://api.github.com/repos/mui/mui-toolpad/issues
        searchParams:
          - name: labels
            value: 'status: needs triage'
          - name: per_page
            value: '100'
        headers: []
        method: GET
    - name: countQuery
      query:
        kind: rest
        url: https://api.github.com/repos/mui/mui-toolpad
        searchParams: []
        headers: []
        method: GET
        transform: return data.open_issues_count
        transformEnabled: true
  display: standalone
