apiVersion: v1
kind: page
spec:
  id: mDJP5kU
  title: Default page
  queries:
    - name: query
      query:
        function: sheetsTest
        kind: local
  content:
    - component: PageRow
      name: pageRow
      children:
        - component: DataGrid
          name: dataGrid
          props:
            rows:
              $$jsExpression: |
                query.data
            columns:
              - field: '0'
                type: string
              - field: '1'
                type: string
              - field: '2'
                type: string
              - field: '3'
                type: string
              - field: '4'
                type: string
              - field: '5'
                type: string
              - field: '6'
                type: string
              - field: '7'
                type: string
              - field: '8'
                type: string
              - field: '9'
                type: string
              - field: '10'
                type: string
              - field: '11'
                type: string
              - field: '12'
                type: string
              - field: '13'
                type: string
              - field: '14'
                type: string
              - field: '15'
                type: string
              - field: '16'
                type: string
              - field: '17'
                type: string
              - field: '18'
                type: string
              - field: '19'
                type: string
