apiVersion: v1
kind: page
spec:
  id: mDJP5kU
  title: Default page
  queries:
    - name: fetchSheet
      query:
        function: fetchSheet
        kind: local
      parameters:
        - name: spreadsheetId
          value:
            $$jsExpression: |
              select.value
        - name: range
          value:
            $$jsExpression: |
              textField.value
    - name: fetchList
      query:
        function: functions.ts#fetchList
        kind: local
      parameters:
        - name: spreadsheetId
          value:
            $$jsExpression: |
              select.value
        - name: range
          value:
            $$jsExpression: |
              textField.value
  content:
    - component: PageRow
      name: pageRow1
      children:
        - component: Select
          name: select
          props:
            label: Choose Spreadsheet
            fullWidth: true
            options:
              $$jsExpression: |
                fetchList.data.map((a) => a.id)
          layout:
            columnSize: 1
        - component: TextField
          name: textField
          props:
            defaultValue: Sheet1!A:Z
            label: Enter range
            fullWidth: true
    - component: PageRow
      name: pageRow
      children:
        - component: DataGrid
          name: dataGrid
          props:
            rows:
              $$jsExpression: |
                fetchSheet.data
            columns:
              - field: name
                type: string
              - field: price
                type: string
              - field: volume
                type: string
              - field: priceopen
                type: string
              - field: high
                type: string
              - field: low
                type: string
              - field: marketcap
                type: string
              - field: tradetime
                type: string
              - field: datadelay
                type: string
              - field: eps
                type: string
              - field: high52
                type: string
              - field: low52
                type: string
              - field: change
                type: string
              - field: closeyest
                type: string
              - field: shares
                type: string
              - field: currency
                type: string
