version: '3.7'

services:
  studio:
    image: janpot/mui-studio:0.0.5-alpha.2
    environment:
      - STUDIO_DATABASE_URL=postgresql://studio-app:secretpw@postgres:5432/postgres?connect_timeout=10
    ports:
      - '3000:3000'

  postgres:
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_USER=studio-app
      - POSTGRES_PASSWORD=secretpw
    logging:
      options:
        max-size: 10m
        max-file: '3'
    expose:
      - '5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
