name: Release Docker images

on:
  workflow_dispatch:
    inputs:
      commit:
        type: string
        required: true
      version:
        type: string
        required: true
      latest:
        type: boolean

permissions: {}

jobs:
  docker-release:
    name: Retag and push
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Debug
        run: |
          echo "commit: ${{ github.event.inputs.commit }}"
          echo "docker tag: ${{ github.event.inputs.version }}"
          echo "latest: ${{ toJSON(github.event.release.latest) }}"

      - name: Login to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish version tag
        uses: akhilerm/tag-push-action@85bf542f43f5f2060ef76262a67ee3607cb6db37 # v2.1.0
        with:
          src: docker.io/muicom/toolpad:${{ github.event.inputs.commit }}
          dst: docker.io/muicom/toolpad:${{ github.event.inputs.version }}

      - name: Publish latest tag
        uses: akhilerm/tag-push-action@85bf542f43f5f2060ef76262a67ee3607cb6db37 # v2.1.0
        if: ${{ github.event.inputs.latest == 'true' }}
        with:
          src: docker.io/muicom/toolpad:${{ github.event.inputs.commit }}
          dst: docker.io/muicom/toolpad:latest
